### ISSUE TITLE
[TODO] 添加2.6.2以来的新API

### ISSUE THREAD

**Issue by harry-xi** [LiteLScript-Dev/HelperLib#9]
- [x] setScale API
- [x] ItemAPI::setDisplayName
- [x] DeviceAPI::getInputMode for LLSE
- [x] PlayerUseBucket Event
- [x] distanceToPos API for PlayerAPI & EntityAPI
- [x] stopFire API for PlayerAPI & EntityAPI
- [x] more properties in BlockAPI
- [x] EntityAPI : EntityAPI::isBaby EntityAPI::isMoving 
- [x] PlayerAPI : PlayerAPI::isMoving
- [x] player.setTitle()
